### ISSUE TITLE
Admin/Users

### ISSUE THREAD

**Issue by mothstudios** [mothstudios/workflow#10]
I have noticed that there is a text field in Admin/Users that allow for "roles". It would be good if this
could be displayed along with the email address on projects. Not sure how admin is called in program, since it is a gem it is kind of a mystery to me. Is this easy?

It would look something like this:

Producer: Robert Silvey
silsharp@yahoo.com

**Comment by AikedeJongste** [comment]
Yes, this easy to do. Is this field required when creating a project? And what field type should it be? A text field?

**Comment by mothstudios** [comment]
Should be required and should be a text field.

**Comment by AikedeJongste** [comment]
In the codebase roles is a property of a user. And that makes more sense to me too. So it should be required when creating a user (signing up) not when creating a project right? It has nothing to do with a project.

**Comment by AikedeJongste** [comment]
I've added the roles fields to the signup form, the edit user form and the show view of the Project. Screenshots are below and if you want to see the code or try it yourself it's in the Develop branch, not in cal3!

![screen shot 2015-04-03 at 16 56 29](https://cloud.githubusercontent.com/assets/878230/6983912/5fdd20e6-da23-11e4-97b3-a69f1382d7c2.png)
![screen shot 2015-04-03 at 16 52 03](https://cloud.githubusercontent.com/assets/878230/6983910/5fdc5e22-da23-11e4-92cc-38daa8d4d174.png)
![screen shot 2015-04-03 at 16 51 34](https://cloud.githubusercontent.com/assets/878230/6983911/5fdd2c9e-da23-11e4-891a-bbd5f7b81d36.png)

**Comment by AikedeJongste** [comment]
And I've also made roles a required field. So a user will always have a role displayed and the space in the layout will never be empty. 

![screen shot 2015-04-03 at 17 06 27](https://cloud.githubusercontent.com/assets/878230/6983946/de10c9c2-da23-11e4-8cf5-8f82a481350c.png)

Time spent: 15 minutes which is 15 dollar
