### ISSUE TITLE
Bob comments

### ISSUE THREAD

**Issue by mothstudios** [mothstudios/workflow#2]
Moving in the right direction. Video works, able to add events, day view on project.
Here is a list of changes, some relating to the original email I sent you and others that are related to usability - let me know your thoughts. Let me know if some of these are additional charges and I will update the amount I send you. 
Thanks again. B

EVENTS/CALENDAR:
-currently each project can create events for scheduling.
if you change projects the events from the previous project disappear. Either the events
page should show ALL projects for that particular user or ALL projects should be available for viewing on the project page of every project for that user as well. Not sure what is easier to accomplish

-event calendar should be on the event page not at root
from your email: 
The homepage for the app is defined als home#index in the routes file. 
from your email: 
If you want to see events out of their project context you have to change the events controller, because it only show the events linked to a project

-cannot change calendar events - change time etc - in either full calendar view or daily view on project page

PROJECTS:
-Update does not work. Only able to update from admin

VIDEO:
I see that the html5 will render “BigBuckBunny"
Issue: slow load time for video- no poster frame, from user perspective looks like something is wrong
 until video loads

Here is a list of html 5 video skins/players - some free some not free:
http://spyrestudios.com/10-html-5-video-players/

Eventually I want to be able to do is to set in and out points on the video for the process of making changes. So in theory you would  click a button that is labeled “in" at say 1:00 and “out" at 1:30 - and make a comment like "please remove clip”.
and you would see in the comment window   — 1:00-1:30 please remove clip
I do not need to do this right away, but some players and API’s have some of this built in and some do not - trying to move toward that direction, hope that makes sense.

**Comment by AikedeJongste** [comment]
Hi Bob, I moved all items above to separate issues so we can discuss and fix them one at a time.

**Comment by mothstudios** [comment]
Thanks Aike, good to learn a little bit more about proper workflow
using Github.
Bob 

----- Original Message -----
