### ISSUE TITLE
Show all events for current user on projects page.

### ISSUE THREAD

**Issue by AikedeJongste** [mothstudios/workflow#3]
Currently each project can create events for scheduling. If you change projects the events from the previous project disappear. Either the events
page should show ALL events for that particular user or ALL events should be available for viewing on the project page of every project for that user as well. Not sure what is easier to accomplish

**Comment by AikedeJongste** [comment]
Do you mean events instead of projects?

Either the events page should show ALL ~~projects~~ events?? for that particular user or ALL ~~projects~~ events should be available for viewing on the project page of every project for that user as well. Not sure what is easier to accomplish

**Comment by mothstudios** [comment]
yes. Any thought on this?

**Comment by AikedeJongste** [comment]
I think the calendar on the projects page should show only events linked to that project.

**Comment by mothstudios** [comment]
OK.

**Comment by AikedeJongste** [comment]
Done! Please close the issue if it works as expected.
