### ISSUE TITLE
Event calendar should be on the event page not at root

### ISSUE THREAD

**Issue by AikedeJongste** [mothstudios/workflow#4]
-event calendar should be on the event page not at root
from your email: 
The homepage for the app is defined als home#index in the routes file. 
from your email: 
If you want to see events out of their project context you have to change the events controller, because it only show the events linked to a project

**Comment by AikedeJongste** [comment]
This is what the startpage/landingpage/root of the app looks like now:

![screen shot 2015-03-11 at 09 53 52](https://cloud.githubusercontent.com/assets/878230/6593025/9240182e-c7d4-11e4-9113-6289d7f15af3.png)

**Comment by AikedeJongste** [comment]
![screen shot 2015-03-11 at 09 55 56](https://cloud.githubusercontent.com/assets/878230/6593048/daa3bd1e-c7d4-11e4-8b1c-55a27d226a56.png)

if you click on the "54ab2ff" you can see the commit with the changes I made to do this. If you're satisfied with the result you can close this issue. If not, please explain how you do want it.

**Comment by mothstudios** [comment]
event/calendar is no longer on the homepage, but does not work on the events page. I get an error.
project without id

![screen shot 2015-03-12 at 1 50 10 pm](https://cloud.githubusercontent.com/assets/8615211/6610231/3a9f22a2-c8c1-11e4-9df7-9f15782b5999.png)

**Comment by AikedeJongste** [comment]
Do you want an events page (http://localhost:3000/events) that displays all events from all projects? It doesn't work like that now, but what does work is the page with all events that belong to a project: http://localhost:3000/projects/1/events

**Comment by mothstudios** [comment]
yes, I would like an events page as well where you can look at the events for the day,week, month.
I think it would be good for the artist(user) to be able to look at all projects, belonging to that user, on the
events page. Is that possible?

**Comment by AikedeJongste** [comment]
So the events page shows all events that belong to all projects that belong to the current user?

**Comment by mothstudios** [comment]
Correct. Is that possible?

**Comment by AikedeJongste** [comment]
@mothstudios I fixed the events page, please close the issue if this is what you want.
