### ISSUE TITLE
Update projects bug

### ISSUE THREAD

**Issue by AikedeJongste** [mothstudios/workflow#6]
Update does not work. Only able to update from admin

**Comment by AikedeJongste** [comment]
![screen shot 2015-03-11 at 10 18 59](https://cloud.githubusercontent.com/assets/878230/6593339/13e009a4-c7d8-11e4-8b7d-398c28d87b2d.png)

You can now click edit and change the projects properties. I used @project.update_attributes(project_params) instead of @project.save. 

If this is what you want please close the issue with the button below, otherwise please explain how I can reproduce the bug.

**Comment by AikedeJongste** [comment]
@mothstudios can you confirm that this problem is solved and close the issue?

**Comment by mothstudios** [comment]
sorry, yes it is correct.
