### ISSUE TITLE
Better video player

### ISSUE THREAD

**Issue by AikedeJongste** [mothstudios/workflow#7]
VIDEO:
I see that the html5 will render “BigBuckBunny"
Issue: slow load time for video- no poster frame, from user perspective looks like something is wrong
until video loads

Here is a list of html 5 video skins/players - some free some not free:
http://spyrestudios.com/10-html-5-video-players/

Comment from Bob:
Eventually I want to be able to do is to set in and out points on the video for the process of making changes. So in theory you would click a button that is labeled “in" at say 1:00 and “out" at 1:30 - and make a comment like "please remove clip”.
and you would see in the comment window — 1:00-1:30 please remove clip
I do not need to do this right away, but some players and API’s have some of this built in and some do not - trying to move toward that direction, hope that makes sense.

**Comment by AikedeJongste** [comment]
I think YouTube does this very well, click here for a 6 second splash: https://www.youtube.com/embed/S0_uFKYsAmI?start=104&end=110&version=3&rel=0

it starts at 1:44 and stops at 1:50.

**Comment by mothstudios** [comment]
I am thinking that a user can click on a button that is labeled "in" and "out" and the text "1:44" and "1:50" would move into the comments window with the ability to comment on it. I believe youtube can do notes as well, but that is not what I am interested in.

**Comment by mothstudios** [comment]
Here is an example.
![home-highlight-1](https://cloud.githubusercontent.com/assets/8615211/6681512/8db9ae94-cccc-11e4-9cac-8d7cd794daac.jpg)

**Comment by AikedeJongste** [comment]
Okay, I'm closing this issue because we'll use YouTube/Vimeo for now and do this later.

**Comment by mothstudios** [comment]
Are we able to add the in and out point as I listed as an example, it is important.

**Comment by AikedeJongste** [comment]
Yes!
